## fasta
dna: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_dna_v4.fa
cds: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_cds_v4.fa
cdna: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_cdna_v4.fa
ncrna: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_ncrna_v4.fa
rRNA: /MaizeLab/auhpc1/DataBase/RNAcentral/v16.rRNA/PlantrRNA_RNACentralv16.fa
mirna: /MaizeLab/auhpc1/DataBase/miRBase/22.1/zma_mature.fa
## annotation
bed: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_v4.44.bed
gtf: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma.v4.44.gtf
mrna_gtf: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_mrna.v4.44.gtf
lncrna_gtf: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_lncrna.v4.44.gtf
go: /MaizeLab/auhpc1/DataBase/GO/zma.go
## index
dict: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_dna_v4.fa.dict
splice_sites: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/hisat2Index/zma_v4.44.ss
rRNA_bowtie2_index: /MaizeLab/auhpc1/DataBase/RNAcentral/v16.rRNA/PlantrRNA_RNACentralv16.fa
genome_bowtie2_index: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/Bowtie2Index/genome.fa
genome_hisat2_index: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/hisat2Index/genome.fa
genome_bwa_index: /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/BwaIndex/genome.fa
## db
pfamdb: /MaizeLab/auhpc1/DataBase/Pfam/33.1/Pfam-A/Pfam-A.hmm
pfamdt: /MaizeLab/auhpc1/DataBase/Pfam/33.1/Pfam-A/Pfam-A.hmm.dat
## DEG Analysis needed
compare_pairs: /MaizeLab/auhpc1/liupeng/02.Project/07.LncCirSmk/compare_pairs.txt
sample_groups: /MaizeLab/auhpc1/liupeng/02.Project/07.LncCirSmk/sample_groups.txt
## Trinity needed
TrinitySampleList: /MaizeLab/auhpc1/liupeng/02.Project/07.LncCirSmk/tinity_sample_list.txt
## CIRI2 needed
ciri_quant_cfg: /MaizeLab/auhpc1/liupeng/02.Project/07.LncCirSmk/ciri_quant_cfg.yaml
### Path to a folder where intermediate files will be written.
output_dir: /MaizeLab/auhpc1/liupeng/02.Project/07.LncCirSmk/output.v1/

# Path to a YAML file with samples and their corresponding FASTQ files.
sample_list: /MaizeLab/auhpc1/liupeng/02.Project/07.LncCirSmk/sample.yaml

